# basic options
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: A wonderful site
twitter_username: renikaul
github_username: renikaul

# Build settings
markdown: kramdown
theme: minima
